// statuses
const ERROR = 'ERROR';
const NO_RECORD = 'NO_RECORD';
const NO_AVAILABLE_SLOTS = 'NO_AVAILABLE_SLOTS';
const HAS_AVAILABLE_SLOTS = 'HAS_AVAILABLE_SLOTS';

// cities
const MOSCOW = 'RUS-001';
const EKATERINBURG = 'RUS-033';

module.exports = {
  ERROR,
  NO_RECORD,
  NO_AVAILABLE_SLOTS,
  HAS_AVAILABLE_SLOTS,
  MOSCOW,
  EKATERINBURG,
};
